import Head from "next/head";
import SimpleComponent from "@/components/TitleComponent";
import * as S from "../styles/home";
import SimpleForm from "@/components/SimpleForm";

export default function Home() {
  return (
    <S.Container>
      <Head>
        <title>Jest Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleComponent message="Test Project" />
      <SimpleForm />
    </S.Container>
  );
}
